CREATE TABLE PRODUCTS
(
    ID          BIGINT AUTO_INCREMENT,
    DESCRIPTION VARCHAR(64),
    QUANTITY    INT   NOT NULL,
    PRICE       FLOAT NOT NULL,
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID, UPDATE_TIME)
);


CREATE TABLE SALES
(
    ID             BIGINT AUTO_INCREMENT,
    PRODUCT_ID     BIGINT NOT NULL,
    TOTAL_PRICE    FLOAT  NOT NULL,
    QUANTITY       INT    NOT NULL,
    TRANSACTION_DT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID, TRANSACTION_DT),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS (ID)
);

SET time_zone = 'America/Sao_Paulo';
