version: '3.8'

services:
  sampledb:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass123
      MYSQL_PASSWORD: pass123
      MYSQL_DATABASE: sales
      MYSQL_USER: salesUser
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d